### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [argoproj/argo-site#102]
This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to:
  - A suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), 
  which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks: stages 1, 2 & 3

- [x] Create a GA4 site tag under the **CNCF projects** account.
  The new GA4 stream measurement ID is: **`G-5Z1VTPDL73`**
- [x] [Connect] the following UA IDs from the GA4 web data stream:
  - [x] Main site - `UA-105170809-1`
  - [x] Blog - `UA-105170809-1` - same as main site
  - [x] CD - `UA-105170809-2`
  - [x] ~[cd.apps.argoproj.io](https://cd.apps.argoproj.io) - `UA-105170809-6`, [console](https://analytics.google.com/analytics/web/#/a105170809w220194348p209546310). The site ID appears in [argo-cd-cm.yaml](https://github.com/argoproj/argoproj-deployments/blob/master/argocd/overlays/production/argo-cd-cm.yaml). Look into GA4 for React apps.~ @alexmt says it isn't required
  - [x] Events - `UA-105170809-9`
  - [x] Rollouts - `UA-105170809-3`
  - [x] Workflows - `UA-105170809-7`
- [x] Register domains for cross-domain tracking:
  - [x] Exactly match domain name: `argo-cd.readthedocs.io`
  - [x] Exactly match domain name: `argoproj.github.io` -- all projects other than CD are served from this domain
- [ ] Use GA4 site tag via `gtag.js`:
  - [x] Main site - `UA-105170809-1` - #107
  - [ ] CD
    - [x] Prerequisite: https://github.com/argoproj/argo-cd/issues/10850
    - [x] https://github.com/argoproj/argo-cd/pull/11291
    - [x] https://github.com/argoproj/argo-cd/pull/11323
    - [ ] 2.4
    - [ ] 2.3
    - [ ] 1.8?
  - [x] Events - `UA-105170809-9` - https://github.com/argoproj/argo-events/pull/2237
  - [x] Rollouts - `UA-105170809-3` - https://github.com/argoproj/argo-rollouts/pull/2299
  - [x] Workflows - `UA-105170809-7` - https://github.com/argoproj/argo-workflows/pull/9766
- [ ] Confirm that the GA4 site tag is receiving events from:
  - [x] Main site
  - [x] CD
  - [x] Events
  - [x] Rollouts
  - [x] Workflows
- [ ] Confirm that the UA site tag(s) are still receiving events:
  - [x] Main site - `UA-105170809-1`
  - [ ] CD
  - [x] Events - `UA-105170809-9`
  - [x] Rollouts - `UA-105170809-3`
  - [x] Workflows - `UA-105170809-7`

### Later

- #118

/cc @nate-double-u @caniszczyk 

---

Current website analytics info:

- GA console https://analytics.google.com/analytics/web/#/report-home/a105170809w198079555p192782995
- UA site tag prefix seems to be `UA-105170809` with 
  - `UA-105170809-1`: used by ...
    - This repo? Well, it was at some point, see [8edd65d].
    - [blog.argoproj.io](https://blog.argoproj.io) - which seems to be a custom domain over Medium
  - `UA-105170809-2` used by CD
  - `UA-105170809-3` was assigned to [argo-rollouts](https://github.com/argoproj/argo-rollouts), but isn't currently used.
  - `UA-105170809-7` is used by [argo-workflows](https://github.com/argoproj/argo-workflows):
    https://github.com/argoproj/argo-workflows/blob/3a32b1b4ef30edf02340cbd92004109d1ae1c143/mkdocs.yml#L26-L28
  - `UA-105170809-9` (and previously `UA-105170809-2`?) used by [argo-events](https://github.com/argoproj/argo-events) (https://github.com/argoproj/argo-events/pull/1406):
    https://github.com/argoproj/argo-events/blob/38f5e249cd030935081b5c71fb8129a38e1d2ea9/mkdocs.yml#L12-L14
- The following doc sites don't appear to have GA enabled:
  - https://github.com/argoproj/argo-cd: https://argo-cd.readthedocs.io
  - https://github.com/argoproj/argo-rollouts: https://argoproj.github.io/argo-rollouts

[8edd65d]: https://github.com/argoproj/argo-site/commit/8edd65d4da099133d1cc3abda07c1122b534101a
[connect]: https://support.google.com/analytics/answer/9973999

**Comment by chalin** [comment]
I'd be glad to create a new GA4 site tag under the GA CNCF-projects account if you'd like. We could then link the UA tags to the GA4 tag (and back).

**Comment by chalin** [comment]
Recording here that @alexmt requested that we consolidate accounts (which is the preferred way of managing analytics under GA4).

**Comment by chalin** [comment]
@alexmt - Do you have a preference for the account I use to create the GA4 site tag? The choices are either (a) the CNCF projects account, or (b) your current argo-site account (105170809).

**Edit**: was talking with @caniszczyk, and the CNCF strongly recommends option (a) for all CNCF projects. I'll assume that you're ok with this option and create the account next week if I don't hear from you before then.

**Comment by chalin** [comment]
~@alexmt et all: Can you grant me **contributor access to the Argo Netlify account**? As mentioned elsewhere, given the Argo website setup, I think that it will be simpler to use Netlify snippet injection to setup GA4.~ Oops, scratch that. You're not yet using Netlify.

**Comment by chalin** [comment]
@alexec @sarabala1979 @whynowy - I see that you are editors for the [blog](https://blog.argoproj.io/), which is hosted by Medium. Could you change the config to use the following Google Analytics ID: `G-5Z1VTPDL73` instead of the UA site tag? Thanks. /cc @alexmt

**Comment by chalin** [comment]
> Recording here that @alexmt requested that we consolidate accounts (which is the preferred way of managing analytics under GA4).

@alexmt - do you want the events of the CD app ([cd.apps.argoproj.io](https://cd.apps.argoproj.io/applications)) to also be consolidated together with the rest page view events for the Argo project docs? The app's path is distinct from doc site pages.

**Comment by alexmt** [comment]
Hello @chalin . I think it is not required. We've configured GA for https://cd.apps.argoproj.io/ mostly to get Google Analytics integration feature of Argo CD, not to track how many people visit https://cd.apps.argoproj.io/.

**Comment by chalin** [comment]
I'll assume that you've backported GA4 ID to the older versions of the docs that you felt it necessary for. Closing this issue since `latest`, `stable` and v2.5 have been successfully migrated 🎉
